### ISSUE TITLE
CI Build fails because of dependecies

### ISSUE THREAD

**Issue by mchambaud** [seglo/grunt-connect-prism#18] opened 2015-01-12 22:36 UTC
I'm getting this error when I run npm install

I investigated and found that connect-prism depends on di.js which depends on traceur-compiler. connect-prism is at version 1.0.0 while grunt-connect-prism is ^0.7.6 and other dependencies are not up-to-date.

It would be great if dependencies were updated!

--------

[16:51:11][npm install] npm ERR! notarget No compatible version found: traceur@'vojtajina/traceur-compiler#add-es6-pure-transformer-dist'
[16:51:11][npm install] npm ERR! notarget Valid install targets:
[16:51:11][npm install] npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17","0.0.18","0.0.19","0.0.20","0.0.21","0.0.22","0.0.23","0.0.24","0.0.25","0.0.27","0.0.28","0.0.29","0.0.30","0.0.31","0.0.32","0.0.33","0.0.34","0.0.35","0.0.36","0.0.37","0.0.38","0.0.39","0.0.40","0.0.41","0.0.42","0.0.43","0.0.44","0.0.45","0.0.46","0.0.47","0.0.48","0.0.49","0.0.50","0.0.51","0.0.52","0.0.53","0.0.54","0.0.55","0.0.56","0.0.57","0.0.58","0.0.59","0.0.60","0.0.61","0.0.62","0.0.63","0.0.64","0.0.65","0.0.66","0.0.67","0.0.68","0.0.69","0.0.70","0.0.71","0.0.72","0.0.73","0.0.74","0.0.75","0.0.76","0.0.77","0.0.78","0.0.79","0.0.80","0.0.81"]
[16:51:11][npm install] npm ERR! notarget 
[16:51:11][npm install] npm ERR! notarget This is most likely not a problem with npm itself.
[16:51:11][npm install] npm ERR! notarget In most cases you or one of your dependencies are requesting
[16:51:11][npm install] npm ERR! notarget a package version that doesn't exist.
[16:51:11][npm install] 
[16:51:11][npm install] npm ERR! System Windows_NT 6.2.9200
[16:51:11][npm install] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[16:51:11][npm install] npm ERR! cwd C:\BuildAgent\work\39552a5b2b8d5b22
[16:51:11][npm install] npm ERR! node -v v0.10.35
[16:51:11][npm install] npm ERR! npm -v 1.4.28
[16:51:11][npm install] npm ERR! code ETARGET
[16:51:11][npm install] npm
[16:51:11][npm install] Process exited with code 1

**Comment by mchambaud** [comment] 2015-01-13 14:58
I've done some further testing and it works fine on MAC OS X and Windows environment. It seems the problem is limited to TeamCity Build.

**Comment by seglo** [comment] 2015-01-13 15:24
I'm working on an upcoming release of `connect-prism`.  As you saw on the repo it's at `1.0.0`, but the latest version of `grunt-connect-prism` should be referencing a compatible version of `connect-prism`.  Some others have reported trouble installing the project on Windows, so I'll take a look at this next release.

**Comment by mchambaud** [comment] 2015-01-13 15:34
Ok. We will be needing this a soon as possible. Let me know if I can help.

**Comment by seglo** [comment] 2015-01-13 15:37
Does your project happen to be on github so I can reproduce the error you're seeing?

**Comment by mchambaud** [comment] 2015-01-13 16:30
It it not unfortunately.

**Comment by seglo** [comment] 2015-04-17 01:26
I can't reproduce this.  I'm going to close it until you or someone else can help me reproduce it.

**Closed by seglo** 2015-04-17 01:26 UTC
